config/routes.rb
Rails.application.routes.draw do


  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users, controllers: { registrations: "registrations"}
  
  # as :user do
  #   get '/' => 'devise/registrations#new'
  # end

  devise_for :users


  root to: 'user#index'
  
  # unauthenticated :user do
  #   root to: 'user#index'
  # end

  resources :albums do
    resources :pictures
  end

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :pictures
  has_many_attached :images
  validates :title, presence: true

  before_save(:titleize_title)

  private
    def titleize_title
      self.title = self.title.titleize
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :album
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :albums

  # rails_admin do
  #   configure :user do
  #     label 'Owner of this ball: '
  #   end
  # end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @users = User.all
    @albums = current_user.albums.page(params[:page]).per(11)
    # @albums = Album.order(:title).page(params[:page]).per(11)
    @pictures = Picture.all
    render :index
  end

  def new
    # @user = User.find(params[:id])
    @album = current_user.albums.build
    render :new
  end

  def create
    # User.all
    @album = current_user.albums.new(album_params)
    # @album.images.attach(params[:album][:images])
    if @album.save
      flash[:notice] = "album successfully added!"
      redirect_to albums_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    flash[:notice] = "album successfully edited!"
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    # # @picture = @album.pictures.new
    # @picture = Picture.find(params[:id])
    @pictures = Picture.all
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      flash[:notice] = "album successfully updated!"
      redirect_to album_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    flash[:notice] = "album successfully deleted!"
    redirect_to albums_path
  end

  def like
    self.favorite = true
    self.save!
  end 

  def unlike
    @album = Album.find(params[:id])
    @album.favorite = false
    @album.save!
  end 

  private
    def album_params
      params.require(:album).permit(:title, :favorite, images: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :authenticate_user!
  def after_sign_in_path_for(resource)
    albums_path
  end

  # def after_sign_in_path_for(resource)
  #   current_user_path
  #  end

  # def current_user
  #   if session[:user_id]
  #     @current_user = User.find(session[:user_id])
  #   end
  # end



  # def current_user
  #   if session[:user_id]
  #     @current_user |= User.find(session[:user_id])
  #   end
  # end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def new
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.new
    render :new
  end

  def create
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.new(picture_params)
    @picture.image.attach(params[:picture][:image])
    if @picture.save
      flash[:notice] = "picture successfully added!"
      redirect_to album_path(@album)
    else
      render :new
    end
  end

    def show 
      @album = Album.find(params[:album_id])
      @picture = Picture.find(params[:id])
      render :show
    end

    def edit
      @album = Album.find(params[:album_id])
      @picture = Picture.find(params[:id])
      render :edit
    end

    def update
      @picture = Picture.find(params[:id])
      if @picture.update(picture_params)
        flash[:notice] = "picture successfully updated!"
        redirect_to album_picture_path(@picture.album)
      else
        @album = Album.find(params[:album_id])
        render :edit
      end
    end

    def destroy
      @picture = Picture.find(params[:id])
      @picture.destroy
      flash[:notice] = "picture successfully deleted!"
      redirect_to album_path(@picture.album)
    end

  private
    def picture_params
      params.require(:picture).permit(:album_id, image: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def show
  end 
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  # before_action :only_see_own_page, only: [:index]

  def index
  end

  def show
  end 

#   def only_see_own_page
#     @user = User.find(params[:id])
  
#     if current_user != @user
#       redirect_to root_path, notice: "Sorry, but you are only allowed to view your own profile page."
#     end
#   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/albums/edit.html.erb
<body id="editAlbum">
  <div class="container backbox">
    <h1 id="newAlbumHeader">Rename Album</h1>
    <br>
    <%= render "layouts/album_form", :object => @album %>
    <br>
    <h1 class="linkBack"><%= link_to "Return to Album", album_path(@album) %></h1>
  </div>
</body>

app/views/albums/index.html.erb
<h1 id="albumsHeader">Albums</h1>
  <% if @albums.any? %>
    <% @albums.each_with_index do |album, index| %>
      <% if index === 0 %>
        <div class="row">
          <div class="col-3 albumCard" style="background-image: url(<%= "#{Faker::LoremFlickr.image(search_terms: ["#{album.title}"])}" %>)">
            <h5 class="gridText"><%= link_to album.title, album_path(album) %></h5>
          </div>
      <% elsif index % 3 === 0 %>
        </div>
        <div class="row">
          <div class="col-3 albumCard" style="background-image: url(<%= "#{Faker::LoremFlickr.image(search_terms: ["#{album.title}"])}"%>)">
            <h5 class="gridText"><%= link_to album.title, album_path(album) %></h5>
          </div>
      <% else %>
        <div class="col-3 albumCard" style="background-image: url(<%= "#{Faker::LoremFlickr.image(search_terms: ["#{album.title}"])}"%>)">
          <h5 class="gridText"><%= link_to album.title, album_path(album) %></h5>
        </div>
      <% end %>
    <% end %>
    <div class="col-3" id="addNewalbum">
      <h3 class="newalbumText"><%= link_to "Add album", new_album_path %></h3>
    </div>
  <% else %>
    <h3>There are no albums yet. <%= link_to "Add album", new_album_path %></h3>
  <% end %>
  <%= paginate @albums %>
  <% @users.each do |user| %>
    <p><%= link_to user.email %></p>
  <% end %>
</div>

app/views/albums/new.html.erb
<body id="newAlbum">
  <div class="container backbox">
    <h1 id="newAlbumHeader">Add a New Album:</h1>
    <br>
    <%= render "layouts/album_form", :object => @album %>
    <br>
    <h1 class="linkBack"><%= link_to "Return to albums", albums_path(@album) %></h1>
  </div>
</body>

app/views/albums/show.html.erb
<body id="albumShow">
  <div class="container backbox">
    <div class="row">
      <div class="col albumPage">
        <br>
        <h1 class="albumHeader"><%= @album.title %></h1>
        <br>
        <% if @album.pictures.any? %>
          <div class="row">
          <% @album.pictures.each do |picture| %>
            <% if picture.image.attached? %>
              <div class="col-3 albumPics">
                <%= image_tag(picture.image, class: "albumPic")  %>
                <%= link_to "Delete", album_path(@album), :data => {:confirm => "You sure?", :method => "delete"}, class: "deleteLink" %>
              </div>
            <% end %>
          <% end %>
          </div>
        <% else %>
          <h2>No pictures are listed for this album.</h2>
        <% end %>
      </div>
      <div class="row">
        <br>
        <br>
        <div class="col-4">
          <h2><%= link_to "Add Picture", new_album_picture_path(@album) %></h2>
        </div>
        <div class="col-4">
          <h2><%= link_to "Edit Album", edit_album_path(@album) %></h2>
        </div>
        <div class="col-4">
          <h2><%= link_to "Delete Album", album_path(@album), :data => {:confirm => "You sure?", :method => "delete"} %></h2>
        </div>
        <br>
        <br>
        <h1 class="linkBack"><%= link_to "Return to albums", albums_path(@album) %></h1>
      </div>
    </div>
  </div>
</body>

app/views/layouts/_album_form.html.erb
<%= render "layouts/errors", :object => @album %>

<h2><%= form_for [@album] do |f| %>
  <%= f.text_field :title, class: "form-control" %>
  <span id="newAlbumSubmit"><%= f.submit %></span>
<% end %></h2>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_picture_form.html.erb
      <%= form_for [@album, @picture] do |f| %>
      <%= f.file_field :image %>
      <%= f.submit %>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo Hunt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class ="links">
  <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %> | <%= link_to "Edit Account", '/users/edit' %>
    <% else %>
      <%= link_to "Sign up", '/users/sign_up' %> | <%= link_to "Sign in", '/users/sign_in' %>
    <% end %>
  </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
    <div class="row">
      <div class="col">
      </div>
      <div class="col">
        <h1><%= @album.title %></h1>

        <%= render "layouts/picture_form", :object => @picture %>
      </div>
    
  </div>
    <h3 class="linkBack"><%= link_to "Return to album", album_path(@album) %></h3>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/user/index.html.erb
<div class="container">

<h1>Photos Home Page</h1>
 
</div>

<%# if current_user %>
<%# end %>